### ISSUE TITLE
Feature request: generalised extra match spacing

### ISSUE THREAD

**Issue by prophile** [PeterJCLaw/srcomp#24]
We currently have a feature to allow extra match spacing at the start of the league. It would be good to get a generalised feature positioning this later on in the league, particularly around shift changes.

**Comment by PeterJCLaw** [comment]
This already exists? The "extra spacing" stuff takes a match number and the amount of time to inject before it.

It doesn't apply to knockout matches, where it might be useful to have something similar, _maybe_.

It also doesn't apply to matches which are the first in their period. (This is intentional since there is expected to already be a large gap before such matches).

**Comment by prophile** [comment]
Ah neat, I thought you were doing it with delays.

**Comment by PeterJCLaw** [comment]
Sounds like this is sorted then? (feel free to re-open if not)
